#!/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2022 Colin B. Macdonald

#xmllint --noout - << EOF
#<pl-question-root>
#</pl-question-root>
#EOF

A=tmp_file_needs_autogen_name

echo "<pl-question-root>" > $A
cat $1 >> $A
echo "</pl-question-root>" >> $A

xmllint --noout $A

rm -f $A
